#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}

umask "$UMASK_SET"

exec \
	s6-setuidgid abc syncthing \
	-home=/config -no-browser -no-restart \
	--gui-apikey=$APIKEY \
	--gui-address="0.0.0.0:8384"
